import {
  CopilotRuntime,
  ExperimentalEmptyAdapter,
  copilotRuntimeNextJSAppRouterEndpoint,
} from "@copilotkit/runtime";
import { LlamaIndexAgent } from "@ag-ui/llamaindex";
import { NextRequest } from "next/server";

const serviceAdapter = new ExperimentalEmptyAdapter();

const runtime = new CopilotRuntime({
  agents: {
    my_agent: new LlamaIndexAgent({
      url: "http://localhost:8000/run",
    }),
  },
  // Thread names are auto-generated by default.
  // Set to false to disable:
  generateThreadNames: true,
  // Optional: tune thread lock behavior
  // lockTtlSeconds: 20,              // Lock TTL (default 20s, max 3600s)
  // lockHeartbeatIntervalSeconds: 15, // Heartbeat interval (default 15s, max 3000s)
  // lockKeyPrefix: "my-app",          // Custom Redis key prefix for the lock

  // Enable A2UI
  a2ui: {},
});

const handleRequest = async (req: NextRequest) => {
  const { handleRequest: handler } = copilotRuntimeNextJSAppRouterEndpoint({
    runtime,
    serviceAdapter,
    endpoint: "/api/copilotkit",
  });
  return handler(req);
};

export const POST = handleRequest;
export const GET = handleRequest;
